### ISSUE TITLE
Neexistující ValueObject apple_pay a google_pay

### ISSUE THREAD

**Issue by RadH-CZ** [ThePay/api-client#35]
### Description

```markdown
Do formuláře doplňujeme povolené metody pomocí TheClient->getActivePaymentMethods()->all().
Tam jsou apple_pay a google_pay dostupné.

Při vytvoření platby ale skončí chybou InvalidArgumentException:
"apple_pay in not valid value" a "google_pay in not valid value"

TheClient->createPayment($params, 'apple_pay');
"L269: $paymentMethod = $methodCode === null ? null : new PaymentMethodCode($methodCode);"

V https://github.com/ThePay/api-client/blob/v1.x/src/ValueObject/PaymentMethodCode.php chybí dvě hodnoty apple_pay a google_pay.
```

### Environment

Production

### PHP version

7.0

### SDK version

1.3.3, 1.5.1

**Comment by Triplkrypl** [comment]
Thanks for reporting problem, `PaymentMethodCode` is enum value object, but this do not make sense any more.
Active payment methods is dynamic content and keep static enum up to date can be hard and can cause errors like this.

We made fix: https://github.com/ThePay/api-client/commit/800d2e656f0008e50e4e1ac7ca3fb4e06eeeb07f, released in version: https://github.com/ThePay/api-client/releases/tag/v1.3.4.
`PaymentMethodCode` still extends `EnumValueObject` for better backward compatibility, but value is not validated in constructor, only on our server side.

You mention SDK version 1.3.3, **you need update the 1.3.3 version** to avoid problems with new payment methods.
**This update is also recommended for everyone else.**
