### ISSUE TITLE
Nelze zadávat platbu při nedefinici telefonního čísla

### ISSUE THREAD

**Issue by Skalin** [ThePay/api-client#73]
### Description

Při vytvoření platby spolu s Customer entitou je dle [dokumentace](https://thepay.docs.apiary.io/#reference/data-retrieval/payments/create-new-payment) nepovinné zadávat telefonní číslo, pokud je přítomen e-mail.

Entita CreatePaymentCustomer však vyžaduje jako 4. parametr zadání telefonu, který je nullable.
Při zadání null platba spadne na "incorrect MSISDN format", protože se do API posílá implicitně prázdný string.
```
InvalidArgumentException: Phone number: "" is not in correct MSISDN format. in 
/vendor/thepay/api-client/src/ValueObject/PhoneNumber.php:17
```

V rámci API se tedy někde implicitně null přetypuje na prázdný string a způsobí nedokončení platby.

Lze prosím zkontrolovat, že je takto v pořádku? Dle mého názoru není toto chování v souladu s dokumentací.

### PHP version

7.4

### SDK version

1.7.0

**Comment by Triplkrypl** [comment]
@Skalin Are you sure, you are using 1.7.0 version?

Your exception is from line 17, but in 1.7.0 version is the exception on line 20: https://github.com/ThePay/api-client/blob/8e94f749153abb688d2f48065fa3e52808bd14b6/src/ValueObject/PhoneNumber.php#L20

```
InvalidArgumentException: Phone number: "" is not in correct MSISDN format. in 
/vendor/thepay/api-client/src/ValueObject/PhoneNumber.php:17
```

We already make fix in version **1.3.3** https://github.com/ThePay/api-client/commit/b9664f3.

You should update SDK at least on 1.3.3 version or greater.
